//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ASantiagoEvalucacionTecnicaLumenEntities : DbContext
    {
        public ASantiagoEvalucacionTecnicaLumenEntities()
            : base("name=ASantiagoEvalucacionTecnicaLumenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Promocion> Promocions { get; set; }
    
        public virtual ObjectResult<ProductoGetAll_Result> ProductoGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductoGetAll_Result>("ProductoGetAll");
        }
    
        public virtual ObjectResult<ProductoGetAllMostrar_Result> ProductoGetAllMostrar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductoGetAllMostrar_Result>("ProductoGetAllMostrar");
        }
    
        public virtual ObjectResult<ProductoGetByMarca_Result> ProductoGetByMarca(Nullable<int> idMarca)
        {
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("IdMarca", idMarca) :
                new ObjectParameter("IdMarca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductoGetByMarca_Result>("ProductoGetByMarca", idMarcaParameter);
        }
    
        public virtual ObjectResult<ProductoGetByNombre_Result> ProductoGetByNombre(string nombreProducto)
        {
            var nombreProductoParameter = nombreProducto != null ?
                new ObjectParameter("NombreProducto", nombreProducto) :
                new ObjectParameter("NombreProducto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductoGetByNombre_Result>("ProductoGetByNombre", nombreProductoParameter);
        }
    
        public virtual ObjectResult<PromocionGetAllActiva_Result> PromocionGetAllActiva()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PromocionGetAllActiva_Result>("PromocionGetAllActiva");
        }
    
        public virtual ObjectResult<MarcaGetAll_Result> MarcaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarcaGetAll_Result>("MarcaGetAll");
        }
    }
}
